name: Check, Build & Deploy

on:
  push:
    paths-ignore:
      - "README.md"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "14.18.2"

      - name: Install Dependencies
        run: yarn

      - name: Svelte Check
        run: yarn run check

      - name: Build
        run: yarn run build:deploy

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
